<?php
# 
# This file is part of Roundcube "plugin_manager" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2014 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Tilläggshanterare';
$labels['plugin_manager_title']='Hantera tillägg';
$labels['updatepm']='Tilläggshanterar uppdatering finns.';
$labels['updatepmrequired']='Tilläggshanterar uppdatering krävs.';
$labels['downloadnow']='Ladda ner nu';
$labels['homepage']='Hemsida';
$labels['misc']='Diverse';
$labels['downloads']='nedladdningar';
$labels['showall']='Visa alla tillägg';
$labels['hideuptodate']='Visa endast uppdateringar';
$labels['trylater']='Vänligen försök senare...';
$labels['translate']='Översätt detta tillägg';
$labels['translationaccount']='Realtids överättningskonto (användarnamn)';
$labels['translationserver']='Realtids översättningskonto (lösenord)';
$labels['whatsthis']='Vad är detta?';
$labels['restoredefaults']='Återgå till grundinställningarna';
$labels['checkall']='Markera alla';
$labels['uncheckall']='Avmarkera alla';
$labels['status']='Status';
$labels['globalplugins']='Globala tillägg';
$labels['performance']='Prestanda';
$labels['backend']='Servertillägg';
$labels['messagesmanagement']='Meddelandehantering';
$labels['furtherconfig']='Vill du konfigurera detta tillägg nu?';
$labels['successfullysaved']='Sparats';
$labels['errorsaving']='Ett fel inträffade vid sparning.';
$labels['yes']='Ja';
$labels['no']='Nej';
$labels['disable']='Avaktivera';
$labels['remove']='Ta bort';
$labels['savewarning']='Vill du spara ändringar redan?';
$labels['plugin_manager_update']='Uppdatera tillägg';
$labels['requiredby']='Tillägget krävs av';
$labels['requires']='Tillägget kräver';
$labels['recommended']='Rekommenderade tillägg';
$labels['update_plugins']='Ladda ner tillägg';
$labels['ziparchive']='Ladda ner zip-fil';
$labels['serverversion']='Server Version';
$labels['orhigher']='eller högre';
$labels['rc_ok']='Roundcube Core är aktuell.';
$labels['noupdates']='Inga uppdateringar valda.';
$labels['rc_update']='RoundCube Core är inaktuell. Vänligen uppdatera.';
$labels['rc_uptodate']='Roundcube Core är aktuell.';
$labels['guide']='Läs mer...';
$labels['develsite']='Ladda ner';
$labels['notinstalled']='inte installerad';
$labels['notregistered']='inte registrerad';
$labels['roundcubeurl']='Ladda ner Roundcube';
$labels['customer_id']='Kundnummer';
$labels['history']='Kontohistorik';
$labels['details']='Detaljer';
$labels['receipt']='Kvitto';
$labels['plugins']='Tillägg';
$labels['clickhere']='Klicka här';
$labels['sum']='Summa';
$labels['show']='Visa';
$labels['hide']='Dölj';
$labels['view']='se';
$labels['submenuprefix']='» ';
$labels['thank_you']='Tack!';
$labels['done']='Klar';
$labels['manage_admins']='Administratörer';
$labels['share_credits']='Dela mina MyRC$ krediter';
$labels['add']='Lägg till';
$labels['switch']='Växla';
$labels['serverconfiguration']='Serverkonfiguration';
$labels['pluginsconfiguration']='Tilläggskonfiguration';
$labels['maintenance_mode']='Underhållsläge';
$labels['systemadmin']='Systemdministratör';
$labels['admin']='Adminstratör';
$labels['enabled']='Aktiverad<br>(standardt)';
$labels['protected']='Skyddad';
$labels['skins']='Skal';
$labels['loads_always']='obligatorisk';
$labels['loads_never']='Tillägget är inaktiverat';
$labels['loads_by_user']='Användaren kan bestämma dess användning';
$labels['loads_linked']='bunden till';
$labels['bind']='bind';
$labels['addplugin']='Lägg till tillägg';
$labels['removeplugin']='Ta bort tillägg';
$labels['errorplugin']='Fel: Obligatorisk tillägg saknas';
$labels['errorrcversion']='Fel: Tillägget kräver Roundcube';
$labels['errorphpversion']='Fel: Tillägget kräver PHP';
$labels['errorphpcurl']='Fel: cURL är inte installerad';
$labels['errorphpfinfo']='Fel: finfo är inte installerad';
$labels['errordb8']='Databas justering krävs';
$labels['syntaxerror']='PHP Syntax Error';
$labels['select_plugin']='Välj tillägg';
$labels['PHPMyAdmin']='PHPMyAdmin';
$labels['openpgpjs_pluginname']='OpenPGPjs';
$labels['tinymce_pluginname']='TinyMCE - HTML Redigerare';
$labels['lang_sel_pluginname']='Välj språk';
$labels['lang_sel_plugindescription']='Välj språk på inloggningssidan';
$labels['newuser_pluginname']='Ny användare';
$labels['sabredav_pluginname']='SabreDAV';
$labels['savepassword_pluginname']='Spara lösenord';
$labels['help_pluginname']='Hjälp';
$labels['help_plugindescription']='Webbmail hjälp';
$labels['rcguard_pluginname']='ReCAPTCHA';
$labels['filters_pluginname']='Filter';
$labels['forgot_password_pluginname']='Glömt lösenord';
$labels['password_pluginname']='Ändra lösenord';
$labels['dkimstatus_pluginname']='DKIM status';
$labels['automatic_addressbook_pluginname']='Automatisk adressbok';