<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['webmailnotifieraddon'] = 'Získat doplněk %s Webmail Notifier';
$labels['webmailnotifierscript'] = 'Získat skript %s Webmail Notifier';
$labels['webmailnotifierflag'] = 'Upozornit na vlajku';
$labels['webmailnotifierfolders'] = 'Zkontrolovat složky';
$labels['recent'] = 'Nové';
$labels['unseen'] = 'Nepřečtené';

?>