<?php
$labels = array();
$labels['pluginname'] = 'Browser Benachrichtigung';
$labels['plugindescription'] = '%s Benachrichtigung bei neuen Nachrichten.';
$labels['webmailnotifieraddon'] = '%s Webmail Notifier Addon';
$labels['webmailnotifierscript'] = '%s Webmail Notifier Script';
$labels['webmailnotifierflag'] = 'Benachrichtigung bei Status';
$labels['webmailnotifierfolders'] = 'Ordner überprüfen';
$labels['recent'] = 'Neu';
$labels['unseen'] = 'Ungelesen';
$labels['tutorial'] = 'Anleitung';
?>