<?php

/*
+-----------------------------------------------------------------------+
| ./plugins/webmail_notifier/localization/en_GB.inc
|
| Language file of MyRoundcube Plugins Bundle
| Copyright (C) 2010-2012, Roland 'rosali' Liebl
|
+-----------------------------------------------------------------------+
| Author: myroundcube@mail4us.net - 03/20/2012 09:36:26
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Webmail Notifier';
$labels['plugindescription'] = 'A Browser Addon to notify on new messages.';
$labels['webmailnotifieraddon'] = 'Get %s Webmail Notifier Addon';
$labels['webmailnotifierscript'] = 'Get %s Webmail Notifier Script';
$labels['webmailnotifierflag'] = 'Notifiy on flag';
$labels['webmailnotifierfolders'] = 'Check folders';
$labels['recent'] = 'New';
$labels['unseen'] = 'Unread';

?>