<?php
$labels = array();
$labels['pluginname'] = 'Webmail Notifier';
$labels['plugindescription'] = 'A Browser Addon to notify on new messages.';
$labels['webmailnotifieraddon'] = 'Get %s Webmail Notifier Addon';
$labels['webmailnotifierscript'] = 'Get %s Webmail Notifier Script';
$labels['webmailnotifierflag'] = 'Notifiy on flag';
$labels['webmailnotifierfolders'] = 'Check folders';
$labels['recent'] = 'New';
$labels['unseen'] = 'Unread';
$labels['tutorial'] = 'Tutorial';
?>