<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 10/02/2012 15:00:43
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Notificador Webmail';
$labels['plugindescription'] = 'Un complemento del navegador para la notificación de nuevos mensajes.';
$labels['webmailnotifieraddon'] = 'Descarga el complemento de notificación de correo nuevo para %s';
$labels['webmailnotifierscript'] = 'Descarga el script de notificación de correo nuevo para %s';
$labels['webmailnotifierflag'] = 'Notificar si hay mensajes';
$labels['webmailnotifierfolders'] = 'Comprobar carpetas';
$labels['recent'] = 'Nuevos';
$labels['unseen'] = 'No leídos';
$labels['tutorial'] = 'Tutorial';

?>