<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 12/11/2012 12:13:25
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Webmail Notifier';
$labels['plugindescription'] = 'Un addon pour la notification des nouveaux messages.';
$labels['webmailnotifieraddon'] = 'Téléchargez le module %s Webmail Notifier';
$labels['webmailnotifierscript'] = 'Téléchargez le script pour %s Webmail Notifier';
$labels['webmailnotifierflag'] = 'Notifiez la reception par un drapeau';
$labels['webmailnotifierfolders'] = 'Vérification des répertoires';
$labels['recent'] = 'Nouveaux';
$labels['unseen'] = 'Non lus';
$labels['tutorial'] = 'Didacticiel';

?>