<?php
$labels = array();
$labels['webmailnotifieraddon'] = 'Descargar o plugin de notificación de correo novo para %s';
$labels['webmailnotifierscript'] = 'Descargar o script de notificación de correo novo para %s';
$labels['webmailnotifierflag'] = 'Notificar se hai mensaxes';
$labels['webmailnotifierfolders'] = 'Comprobar cartafoles';
$labels['recent'] = 'novas';
$labels['unseen'] = 'sen ler';
?>