<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Notifica Webmail';
$labels['plugindescription'] = 'Un Componente  Aggiuntivo per notificare l\'arrivo di un nuovo messaggio.';
$labels['webmailnotifieraddon'] = 'Acquisisci %s Webmail Notifier Addon';
$labels['webmailnotifierscript'] = 'Acquisisci %s Webmail Notifier Script';
$labels['webmailnotifierflag'] = 'Notifica su flag';
$labels['webmailnotifierfolders'] = 'Controlla cartelle';
$labels['recent'] = 'Nuovo';
$labels['unseen'] = 'Non letto';

?>