<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Emiel Wieldraaijer - 12/26/2012 20:20:11
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Webmail berichtgeving';
$labels['plugindescription'] = 'Een browser toevoeging welke u melding geeft indien er nieuwe berichten zijn.';
$labels['webmailnotifierfolders'] = 'Controleer mappen';
$labels['recent'] = 'Nieuw';
$labels['unseen'] = 'Ongelezen';
$labels['tutorial'] = 'Handleiding';

?>