<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Hedon77 g.rybicki|at|c2n.pl                                                              |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Powiadomienie Webmail';
$labels['plugindescription'] = 'Dodatek informujący o nowych wiadomościach';
$labels['webmailnotifieraddon'] = 'Ściągnij %s Powiadomienie Webmailr dodatek';
$labels['webmailnotifierscript'] = 'Ściągnij %s Powiadomienie Webmail skrypt';
$labels['webmailnotifierflag'] = 'Informuj przy fladze';
$labels['webmailnotifierfolders'] = 'Sprawdź katalogi';
$labels['recent'] = 'Nowy';
$labels['unseen'] = 'Nieprzeczytanych';
$labels['tutorial'] = 'Samouczek';

?>