<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                              |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author:                                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['pluginname'] = 'Noticiador de Webmail';
$labels['plugindescription'] = 'Um complemento para noticiar novas mensagens.';
$labels['webmailnotifieraddon'] = 'Pegue o complemento de Notificação de Webmail do %s';
$labels['webmailnotifierscript'] = 'Pegue o scrip de Notificação de Webmail do %s';
$labels['webmailnotifierflag'] = 'Notificar ao marcar';
$labels['webmailnotifierfolders'] = 'Verificar pastas';
$labels['recent'] = 'Novo';
$labels['unseen'] = 'Não lida';

