<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/webmail_notifier/localization/ru_RU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Pavel - 02/12/2013 08:04:20
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Уведомления ВебПочты';
$labels['plugindescription'] = 'Дополнение к для уведомления о новых входящих сообщениях.';
$labels['webmailnotifieraddon'] = 'Получить %s Уведомления ВебПочты дополнение';
$labels['webmailnotifierscript'] = 'Получить %s Уведомления ВебПочты скрипт';
$labels['webmailnotifierflag'] = 'Включить Уведомления';
$labels['webmailnotifierfolders'] = 'Проверять Папки';
$labels['recent'] = 'Новые';
$labels['unseen'] = 'Непрочитанные';
$labels['tutorial'] = 'Туториал';

?>