<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: ysliuthomas                                                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['webmailnotifieraddon'] = '取得%s Webmail Notifier 附加元件';
$labels['webmailnotifierscript'] = '取得%s Webmail Notifier 語法';
$labels['webmailnotifierflag'] = '需通知的類型';
$labels['webmailnotifierfolders'] = '檢查資料夾';
$labels['recent'] = '新郵件';
$labels['unseen'] = '未讀郵件';

?>