<?php
# 
# This file is part of Roundcube "carddav_plus" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2014 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.net
# 

$labels=array();
$labels['pluginname']='CardDAV +';
$labels['plugindescription']='Automatische intergratie van adressenboek en laat gebruiker CardDAV servers toevoegen';