<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2014 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Nastavení';
$labels['plugindescription']='Toto je pomocný doplněk. Je využíván několika dalšími doplňky (např. všemi  hmail_* doplňky).';
$labels['menu']='Menu';
$labels['managefolders']='Správa složek';
$labels['account']='Administrace účtu';
$labels['classic']='Výchozí';
$labels['larry']='Larry';
$labels['remotefolders']='Speciální složky';
$labels['myroundcube']='MyRoundCube';
$labels['serversettings_serversettings']='Další nastavení účtu';
$labels['serversettings_description']='Další nastavení účtu';