<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2014 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Einstellungen';
$labels['plugindescription']='Diese Hilfserweiterung wird von einigen anderen Erweiterungen benötigt (z.B. alle hmail_* Erweiterungen).';
$labels['menu']='Menü';
$labels['managefolders']='Ordner verwalten';
$labels['account']='Konto-Einstellungen';
$labels['classic']='Standard';
$labels['larry']='Larry';
$labels['remotefolders']='Spezialordner';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Vorschau Benutzerobfläche';
$labels['serversettings.serversettings']='Weitere Kontoeinstellungen';