<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2014 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Inställningar';
$labels['menu']='Meny';
$labels['managefolders']='Hantera mappar';
$labels['account']='Konto administration';
$labels['classic']='Standard';
$labels['larry']='Larry';
$labels['remotefolders']='Speciella mappar';
$labels['myroundcube']='MinRoundCube';