(function(a,l,k){function g(b){var c=l.console;n[b]||(n[b]=!0,a.migrateWarnings.push(b),c&&(c.warn&&!a.migrateMute)&&(c.warn("JQMIGRATE: "+b),a.migrateTrace&&c.trace&&c.trace()))}function p(b,c,d,e){if(Object.defineProperty)try{Object.defineProperty(b,c,{configurable:!0,enumerable:!0,get:function(){g(e);return d},set:function(a){g(e);d=a}});return}catch(f){}a._definePropertyBroken=!0;b[c]=d}var n={};a.migrateWarnings=[];a.migrateMute=!0;!a.migrateMute&&(l.console&&l.console.log)&&l.console.log("JQMIGRATE: Logging is active");
a.migrateTrace===k&&(a.migrateTrace=!0);a.migrateReset=function(){n={};a.migrateWarnings.length=0};"BackCompat"===document.compatMode&&g("jQuery is not compatible with Quirks Mode");var q=a("<input/>",{size:1}).attr("size")&&a.attrFn,r=a.attr,y=a.attrHooks.value&&a.attrHooks.value.get||function(){return null},z=a.attrHooks.value&&a.attrHooks.value.set||function(){return k},A=/^(?:input|button)$/i,B=/^[238]$/,C=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,
D=/^(?:checked|selected)$/i;p(a,"attrFn",q||{},"jQuery.attrFn is deprecated");a.attr=function(b,c,d,e){var f=c.toLowerCase(),h=b&&b.nodeType;if(e&&(4>r.length&&g("jQuery.fn.attr( props, pass ) is deprecated"),b&&!B.test(h)&&(q?c in q:a.isFunction(a.fn[c]))))return a(b)[c](d);"type"===c&&(d!==k&&A.test(b.nodeName)&&b.parentNode)&&g("Can't change the 'type' of an input or button in IE 6/7/8");!a.attrHooks[f]&&C.test(f)&&(a.attrHooks[f]={get:function(b,c){var d,e=a.prop(b,c);return!0===e||"boolean"!==
typeof e&&(d=b.getAttributeNode(c))&&!1!==d.nodeValue?c.toLowerCase():k},set:function(b,c,d){!1===c?a.removeAttr(b,d):(c=a.propFix[d]||d,c in b&&(b[c]=!0),b.setAttribute(d,d.toLowerCase()));return d}},D.test(f)&&g("jQuery.fn.attr('"+f+"') may use property instead of attribute"));return r.call(a,b,c,d)};a.attrHooks.value={get:function(b,a){var d=(b.nodeName||"").toLowerCase();if("button"===d)return y.apply(this,arguments);"input"!==d&&"option"!==d&&g("jQuery.fn.attr('value') no longer gets properties");
return a in b?b.value:null},set:function(a,c){var d=(a.nodeName||"").toLowerCase();if("button"===d)return z.apply(this,arguments);"input"!==d&&"option"!==d&&g("jQuery.fn.attr('value', val) no longer sets properties");a.value=c}};var m,j,s=a.fn.init,E=a.parseJSON,F=/^([^<]*)(<[\w\W]+>)([^>]*)$/;a.fn.init=function(b,c,d){var e;if(b&&"string"===typeof b&&!a.isPlainObject(c)&&(e=F.exec(a.trim(b)))&&e[0])if("<"!==b.charAt(0)&&g("$(html) HTML strings must start with '<' character"),e[3]&&g("$(html) HTML text after last tag is ignored"),
"#"===e[0].charAt(0)&&(g("HTML string cannot start with a '#' character"),a.error("JQMIGRATE: Invalid selector string (XSS)")),c&&c.context&&(c=c.context),a.parseHTML)return s.call(this,a.parseHTML(e[2],c,!0),c,d);return s.apply(this,arguments)};a.fn.init.prototype=a.fn;a.parseJSON=function(a){return!a&&null!==a?(g("jQuery.parseJSON requires a valid JSON string"),null):E.apply(this,arguments)};a.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||
/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};a.browser||(m=a.uaMatch(navigator.userAgent),j={},m.browser&&(j[m.browser]=!0,j.version=m.version),j.chrome?j.webkit=!0:j.webkit&&(j.safari=!0),a.browser=j);p(a,"browser",a.browser,"jQuery.browser is deprecated");a.sub=function(){function b(a,c){return new b.fn.init(a,c)}a.extend(!0,b,this);b.superclass=this;b.fn=
b.prototype=this();b.fn.constructor=b;b.sub=this.sub;b.fn.init=function(d,e){e&&(e instanceof a&&!(e instanceof b))&&(e=b(e));return a.fn.init.call(this,d,e,c)};b.fn.init.prototype=b.fn;var c=b(document);g("jQuery.sub() is deprecated");return b};a.ajaxSetup({converters:{"text json":a.parseJSON}});var G=a.fn.data;a.fn.data=function(b){var c,d;if((d=this[0])&&"events"===b&&1===arguments.length)if(c=a.data(d,b),d=a._data(d,b),(c===k||c===d)&&d!==k)return g("Use of jQuery.fn.data('events') is deprecated"),
d;return G.apply(this,arguments)};var H=/\/(java|ecma)script/i,I=a.fn.andSelf||a.fn.addBack;a.fn.andSelf=function(){g("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()");return I.apply(this,arguments)};a.clean||(a.clean=function(b,c,d,e){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;g("jQuery.clean() is deprecated");var f,h=[];a.merge(h,a.buildFragment(b,c).childNodes);if(d){c=function(a){if(!a.type||H.test(a.type))return e?e.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a)};
for(b=0;null!=(f=h[b]);b++)if(!a.nodeName(f,"script")||!c(f))d.appendChild(f),"undefined"!==typeof f.getElementsByTagName&&(f=a.grep(a.merge([],f.getElementsByTagName("script")),c),h.splice.apply(h,[b+1,0].concat(f)),b+=f.length)}return h});var J=a.event.add,K=a.event.remove,L=a.event.trigger,M=a.fn.toggle,t=a.fn.live,u=a.fn.die,v=/\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\b/,w=/(?:^|\s)hover(\.\S+|)\b/,x=function(b){if("string"!==typeof b||a.event.special.hover)return b;
w.test(b)&&g("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'");return b&&b.replace(w,"mouseenter$1 mouseleave$1")};a.event.props&&"attrChange"!==a.event.props[0]&&a.event.props.unshift("attrChange","attrName","relatedNode","srcElement");a.event.dispatch&&p(a.event,"handle",a.event.dispatch,"jQuery.event.handle is undocumented and deprecated");a.event.add=function(a,c,d,e,f){a!==document&&v.test(c)&&g("AJAX events should be attached to document: "+c);J.call(this,a,x(c||""),d,e,f)};
a.event.remove=function(a,c,d,e,f){K.call(this,a,x(c)||"",d,e,f)};a.fn.error=function(){var a=Array.prototype.slice.call(arguments,0);g("jQuery.fn.error() is deprecated");a.splice(0,0,"error");if(arguments.length)return this.bind.apply(this,a);this.triggerHandler.apply(this,a);return this};a.fn.toggle=function(b,c){if(!a.isFunction(b)||!a.isFunction(c))return M.apply(this,arguments);g("jQuery.fn.toggle(handler, handler...) is deprecated");var d=arguments,e=b.guid||a.guid++,f=0,h=function(c){var e=
(a._data(this,"lastToggle"+b.guid)||0)%f;a._data(this,"lastToggle"+b.guid,e+1);c.preventDefault();return d[e].apply(this,arguments)||!1};for(h.guid=e;f<d.length;)d[f++].guid=e;return this.click(h)};a.fn.live=function(b,c,d){g("jQuery.fn.live() is deprecated");if(t)return t.apply(this,arguments);a(this.context).on(b,this.selector,c,d);return this};a.fn.die=function(b,c){g("jQuery.fn.die() is deprecated");if(u)return u.apply(this,arguments);a(this.context).off(b,this.selector||"**",c);return this};
a.event.trigger=function(a,c,d,e){!d&&!v.test(a)&&g("Global events are undocumented and deprecated");return L.call(this,a,c,d||document,e)};a.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(b,c){a.event.special[c]={setup:function(){var b=this;b!==document&&(a.event.add(document,c+"."+a.guid,function(){a.event.trigger(c,null,b,!0)}),a._data(this,c,a.guid++));return!1},teardown:function(){this!==document&&a.event.remove(document,c+"."+a._data(this,c));return!1}}})})(jQuery,
window);