<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/cs_CZ.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: tachec - 04/10/2014 10:50:18
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Pomocný doplněk pro editaci kódu';
$labels['plugindescription'] = 'Jednoduchý doplněk pro editaci kódu.';

?>