<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 08/19/2013 18:34:10
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Hilfserweiterung zum editieren von Code';
$labels['plugindescription'] = 'Hilfserweiterung zum editieren von Code';

?>