<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 10/11/2013 12:11:44
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Complemento auxiliar para la edición de código';
$labels['plugindescription'] = 'Un complemento auxiliar ligero para la edición de código.';

?>