<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/fi_FI.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Markku Virtanen - 10/28/2014 13:57:41
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Lisäliitännäinen koodin muokkausta varten';
$labels['plugindescription'] = 'Kevyt apuliitännäinen koodin muokkausta varten';

?>