<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/pl_PL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Tomasz - 07/28/2013 20:46:46
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Wtyczka wspomagająca edycję kodu';
$labels['plugindescription'] = 'Lekka wtyczka wspomagająca edycję kodu.';

?>