<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/codemirror_ui/localization/sv_SE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Stefan Manninen - 10/31/2014 19:23:08
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Hjälptillägg för kodredigering';
$labels['plugindescription'] = 'Ett lätt hjälptillägg för kodredigering.';

?>