ALTER TABLE events ADD component varchar(6) NOT NULL DEFAULT  'vevent';
ALTER TABLE events ADD organizer varchar(255) DEFAULT NULL;
ALTER TABLE events ADD attendees varchar(255) DEFAULT NULL;
ALTER TABLE events ADD status varchar(25) DEFAULT NULL;
ALTER TABLE events ADD due integer NOT NULL DEFAULT '0';
ALTER TABLE events ADD complete integer NOT NULL DEFAULT '0';
ALTER TABLE events ADD priority integer NOT NULL DEFAULT '0';
ALTER TABLE events DROP "group";
ALTER TABLE events_cache ADD component varchar(6) NOT NULL DEFAULT  'vevent';
ALTER TABLE events_cache ADD organizer varchar(255) DEFAULT NULL;
ALTER TABLE events_cache ADD attendees varchar(255) DEFAULT NULL;
ALTER TABLE events_cache ADD status varchar(25) DEFAULT NULL;
ALTER TABLE events_cache ADD due integer NOT NULL DEFAULT '0';
ALTER TABLE events_cache ADD complete integer NOT NULL DEFAULT '0';
ALTER TABLE events_cache ADD priority integer NOT NULL DEFAULT '0';
ALTER TABLE events_cache DROP "group";
ALTER TABLE events_caldav ADD component varchar(6) NOT NULL DEFAULT  'vevent';
ALTER TABLE events_caldav ADD organizer varchar(255) DEFAULT NULL;
ALTER TABLE events_caldav ADD attendees varchar(255) DEFAULT NULL;
ALTER TABLE events_caldav ADD status varchar(25) DEFAULT NULL;
ALTER TABLE events_caldav ADD due integer NOT NULL DEFAULT '0';
ALTER TABLE events_caldav ADD complete integer NOT NULL DEFAULT '0';
ALTER TABLE events_caldav ADD priority integer NOT NULL DEFAULT '0';
ALTER TABLE events_caldav DROP "group";
UPDATE system SET value='initial|20130512|20130804' WHERE name='myrc_calendar';