<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/de_DE.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 11/25/2013 09:34:54
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Verwalten Sie Ihre Kontakte auf CardDAV-Servern.';
$labels['settings'] = 'CardDAV Einstellungen';
$labels['sharing'] = 'Freigaben';
$labels['share'] = 'Freigeben';
$labels['shareinvitation'] = 'Einladung versenden';
$labels['send'] = 'Versenden';
$labels['cancel'] = 'Abbrechen';
$labels['resource'] = 'CardDAV-Adressbuch';
$labels['label'] = 'Titel';
$labels['url'] = 'URL';
$labels['access'] = 'Zugang';
$labels['username'] = 'Benutzer';
$labels['tutorials'] = 'Tutorials';
$labels['checkresources'] = 'Bitte Resource auswählen';
$labels['checkatleastoneresource'] = 'Bitte wählen Sie zumindest eine Resource aus';
$labels['invitationsubject'] = '%s möchte Ihnen Zugang zu einem CardDAV-Adressbuch gewähren';
$labels['confidentialcarddavaccess'] = 'Vertraulicher CardDAV-Zugang [%s]';
$labels['copytoclipboard'] = 'In die Zwischenablage kopieren';
$labels['copiedtoclipboard'] = 'Die Zwischenablage enthält';
$labels['sharehint'] = 'Geben Sie die obigen Informationen (Benutzername, Passwort (Token) und URLs) an Personen weiter, denen Sie Schreibzugriff auf Ihr Adressbuch gewähren möchten.<br />Ändern oder entfernen Sie den Token, um den Zugang zu schließen.';
$labels['sharehint_readonly'] = 'Geben Sie die obigen Informationen (Benutzername, Passwort (Token) und URLs) an Personen weiter, mit denen Sie Lesezugriff auf Ihr Adressbuch gewähren möchten.<br />Ändern oder entfernen Sie den Token, um den Zugang zu schließen.';
$labels['readwrite'] = 'Schreibzugriff';
$labels['readonly'] = 'Lesezugriff';
$labels['abooktoken'] = 'Token';
$labels['isenabled'] = 'ist aktiviert';
$labels['isdisabled'] = 'ist deaktiviert';
$labels['sync_short'] = 'Abgleich';
$labels['sync'] = 'Kontakte abgleichen';
$labels['add'] = 'Hinzufügen';
$labels['server_url'] = 'CardDAV-Server URL';
$labels['settings_label'] = 'Kategorie';
$labels['settings_read_only'] = 'Nur Lesezugriff';
$labels['settings_curl_not_installed'] = 'Die PHP Erweiterung CURL ist nicht installiert. Bitte installieren Sie CURL um das CardDAV Plugin nutzen zu können.';
$labels['addressbook_contacts'] = 'CardDAV Kontakte';
$labels['settings_empty_values'] = 'Bitte geben Sie eine Kategorie und die URL an';
$labels['settings_saved'] = 'CardDAV Server Einstellungen und vCards erfolgreich gespeichert';
$labels['settings_save_failed'] = 'Beim Speichern der CardDAV Server Einstellungen ist ein Fehler aufgetreten';
$labels['settings_delete_loading'] = 'CardDAV Server Einstellungen und dazugehörige Kontakte werden gelöscht';
$labels['settings_delete_warning'] = 'Sind Sie sicher, dass Sie dieses Adressbuch entfernen möchten?';
$labels['settings_delete_contacts_warning'] = 'Wollen Sie alle Kontakte in diesem Adressbuch endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden! Wählen Sie OK, um das Adressbuch und die Kontakte zu löschen. Wählen Sie ABBRECHEN, um nur das Adressbuch, nicht aber die Kontakte zu löschen.';
$labels['settings_delete_contacts_warning_html'] = 'Wollen Sie alle Kontakte in diesem Adressbuch endgültig löschen?<br />Diese Aktion kann nicht rückgängig gemacht werden!<br /><br />Wählen Sie JA, um das Adressbuch und die Kontakte zu löschen.<br />Wählen Sie NEIN, um nur das Adressbuch, nicht aber die Kontakte zu löschen.';
$labels['settings_deleted'] = 'CardDAV Server Einstellungen wurden erfolgreich gelöscht';
$labels['settings_delete_failed'] = 'Beim Löschen der CardDAV Server Einstellungen ist ein Fehler aufgetreten';
$labels['settings_no_connection'] = 'Es konnte keine Verbindung zum CardDAV Server aufbauen';
$labels['settings_init_server'] = 'Die Verbindung zum CardDAV Server wird überprüft und vCards werden importiert';
$labels['addressbook_synced'] = 'Kontakte wurden erfolgreich abgeglichen';
$labels['addressbook_sync_failed'] = 'Bei der Synchronisierung der Kontakte ist ein Fehler aufgetreten';
$labels['addressbook_sync_loading'] = 'Kontakte werden abgeglichen';
$labels['contact_moved_single'] = 'Kontakt wurde erfolgreich verschoben';
$labels['contact_moved_multiple'] = 'Kontakte wurden erfolgreich verschoben';
$labels['autocomplete'] = 'Autovervoll&shy;ständigung';
$labels['automaticallycollected'] = 'Gesammelte Kontakte';
$labels['automaticallycollected_local'] = 'Gesammelte Kontakte (lokal)';
$labels['useautoabook'] = 'Gesammelte Adressen';
$labels['useforcompletion'] = 'Gesammelte Adressen zur Autovervollständigung verwenden';
$labels['automatic_addressbook'] = 'Adressen beim Senden automatisch hinzufügen zu ...';
$labels['toggle'] = 'umschalten';
$labels['protected'] = 'geschützt';
$labels['defaultaddressbook'] = 'Persönliche Kontakte';
$labels['Global'] = 'Globale Kontakte (Lesezugriff)';
$labels['Work'] = 'Dienstliche Kontakte';
$labels['Family'] = 'Familiäre Kontakte';
$labels['Personal'] = 'Persönliche Kontakte';
$labels['Collected'] = 'Gesammelte Kontakte';
$labels['local'] = 'lokal';
$labels['submenuprefix'] = '» ';
$labels['blank'] = ' ';

?>