<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2014, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 02/09/2014 21:59:32
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Manage CardDAV contacts.';
// $labels['settings'] = 'CardDAV Settings';
$labels['settings'] = 'Sync Settings';
$labels['sharing'] = 'Sharing';
$labels['share'] = 'Share';
$labels['shareinvitation'] = 'Send invitation';
$labels['send'] = 'Send';
$labels['cancel'] = 'Cancel';
$labels['resource'] = 'Resource';
$labels['label'] = 'Label';
$labels['url'] = 'URL';
$labels['access'] = 'Access';
$labels['username'] = 'User';
$labels['tutorials'] = 'Tutorials';
$labels['checkresources'] = 'Check resources';
$labels['checkatleastoneresource'] = 'Please check at least one resource';
$labels['invitationsubject'] = '%s invites you to access CardDAV addressbooks';
$labels['confidentialcarddavaccess'] = 'Confidential CardDAV access [%s]';
$labels['copytoclipboard'] = 'Copy to clipboard';
$labels['copiedtoclipboard'] = 'Copied to clipboard';
$labels['sharehint'] = 'Provide the above information (Username, Password (Token) and URLs) for  others to connect to your shared addressbooks.<br />This information grants read and write access. Change or remove the token to close access.';
$labels['sharehint_readonly'] = 'Provide the above information (Username, Password (Token) and URLs) for  others to connect to your shared addressbooks.<br />This information grants read-only access. Change or remove the token to close access.';
$labels['readwrite'] = 'read/write';
$labels['readonly'] = 'read only';
$labels['abooktoken'] = 'Token';
$labels['isenabled'] = 'is enabled';
$labels['isdisabled'] = 'is disabled';
$labels['sync_short'] = 'Synchronize';
$labels['sync'] = 'Synchronize CardDAVs';
$labels['add'] = 'Add';
$labels['server_url'] = 'CardDAV Server URL';
$labels['settings_label'] = 'Category';
$labels['settings_read_only'] = 'Read only';
$labels['settings_curl_not_installed'] = 'The PHP extension CURL is not installed! Please install CURL to use the CardDAV plugin.';
$labels['addressbook_contacts'] = 'CardDAV contacts';
$labels['settings_empty_values'] = 'Please fill out all Label and URL';
$labels['settings_saved'] = 'CardDAV server settings and vCards saved';
$labels['settings_save_failed'] = 'Failed to save CardDAV server settings';
$labels['settings_delete_loading'] = 'Delete CardDAV server settings and related contacts';
$labels['settings_delete_warning'] = 'Are you sure you want to delete this addressbook?';
$labels['settings_delete_contacts_warning'] = 'Do you want to permanently delete all contacts in this address book? This action can\'t be reverted!  Click OK to delete the address book and all contacts it holds. Click CANCEL to remove the address book from your account but keeping all contacts in this CardDAV resource.';
$labels['settings_delete_contacts_warning_html'] = 'Do you want to permanently delete all contacts in this address book?<br />This action can\'t be reverted!<br /><br />Click OK to delete the address book and all contacts it holds. <br />Click CANCEL to remove the address book from your account but keeping all contacts in this CardDAV resource.';
$labels['settings_deleted'] = 'CardDAV server settings deleted';
$labels['settings_delete_failed'] = 'Failed to delete CardDAV server settings';
$labels['settings_no_connection'] = 'Can\'t connect to the CardDAV server';
$labels['settings_init_server'] = 'Checking CardDAV connection and importing vCards';
$labels['addressbook_synced'] = 'CardDAV contacts synchronized';
$labels['addressbook_sync_failed'] = 'An error occurred while synchronizing CardDAV contacts';
$labels['addressbook_sync_loading'] = 'Synchronize CardDAV contacts';
$labels['contact_moved_single'] = 'contact successfully moved';
$labels['contact_moved_multiple'] = 'contacts successfully moved';
$labels['autocomplete'] = 'Auto­complete';
$labels['automaticallycollected'] = 'Automatically Collected';
$labels['automaticallycollected_local'] = 'Automatically Collected (local)';
$labels['useautoabook'] = 'Use automatic address book';
$labels['useforcompletion'] = 'Use automatically collected addresses for autocompletion';
$labels['automatic_addressbook'] = 'Add automatically collected contacts to...';
$labels['toggle'] = 'toggle';
$labels['protected'] = 'protected';
$labels['defaultaddressbook'] = 'Personal Contacts';
$labels['Global'] = 'Global (readonly)';
$labels['Work'] = 'Work';
$labels['Family'] = 'Family';
$labels['Personal'] = 'Personal';
$labels['Collected'] = 'Collected';
$labels['local'] = 'local';
$labels['submenuprefix'] = '» ';
$labels['blank'] = ' ';

?>