function carddav_share_dialog(){var a=[{text:rcmail.gettext("carddav.send"),click:function(){carddav_share_dialog_validate()}},{text:rcmail.gettext("carddav.cancel"),click:function(){$("#sharedialog").dialog("close")}}];$("#sharedialog").dialog({modal:!0,title:rcmail.gettext("carddav.checkresources"),width:"auto",buttons:a});return!1}
function carddav_share_dialog_validate(){var a=!0;$(".shareinvitation").each(function(){$(this).prop("checked")&&(a=!1)});a?rcmail.display_message(rcmail.gettext("carddav.checkatleastoneresource"),"error"):carddav_share_dialog_submit()}function carddav_share_dialog_submit(){$("#sharedialog").dialog("close");rcmail.http_post("plugin.carddav_shareinvitation",unescape($("#formshareinvitation").serialize()));$(".shareinvitation").prop("checked",!1)}
function carddav_share_compose(){rcmail.open_compose_step({_carddav_share_invitation:1})}
if(window.rcmail){rcmail.addEventListener("init",function(){rcmail.addEventListener("plugin.carddav_server_message",carddav_server_message);rcmail.addEventListener("plugin.carddav_server_success",carddav_server_success);rcmail.addEventListener("plugin.carddav_share_compose",carddav_share_compose);rcmail.register_command("plugin.carddav-server-save",carddav_server_add,!0);rcmail.register_command("plugin.carddav-server-delete",function(a){rcmail.http_post("plugin.carddav-server-delete","_remote=1&_carddav_server_id="+
$.base64Encode(a),rcmail.display_message(rcmail.gettext("settings_delete_loading","carddav"),"loading"))},!0);rcmail.register_command("plugin.carddav-server-remove",function(a){rcmail.http_post("plugin.carddav-server-delete","_remote=1&_remove=1&_carddav_server_id="+$.base64Encode(a),rcmail.display_message(rcmail.gettext("settings_delete_loading","carddav"),"loading"))},!0);$("#_label").keypress(carddav_server_add_enter_event);$("#_server_url").keypress(carddav_server_add_enter_event);$("#_username").keypress(carddav_server_add_enter_event);
$("#_password").keypress(carddav_server_add_enter_event);$(".carddav_edit_label").focus(function(){var a=escape($(this).val());rcmail.env[$(this).attr("id")]=a});$(".carddav_edit_label").blur(function(){var a=$(this).attr("id"),b=encodeURIComponent($(this).val());try{rcmail.env[$(this).attr("id")]!=b&&($("#l"+$(this).attr("id")).css("visibility","visible"),rcmail.http_post("plugin.carddav-label-save","_remote=1&_label="+b+"&_id="+a))}catch(d){}});if($("#rcmfd_default_addressbook").get(0)){var a=$("#rcmfd_default_addressbook").children().get(0);
0==$(a).val()&&$(a).html(rcmail.gettext("carddav.defaultaddressbook")+" ("+rcmail.gettext("carddav.local")+")")}});var carddav_server_add_enter_event=function(a){13==a.keyCode&&carddav_server_add()},carddav_server_readonly=function(a,c){if(-1<a.src.indexOf("checked.png")){a.src=a.src.replace("checked.png","blank.gif");var b=0}else a.src=a.src.replace("blank.gif","checked.png"),b=1;$("#lcarddav_addressbook"+c).css("visibility","visible");rcmail.http_post("plugin.carddav-readonly-save","_remote=1&_readonly="+
b+"&_id="+c)},carddav_server_autocomplete=function(a,c){if(-1<a.src.indexOf("checked.png")){a.src=a.src.replace("checked.png","blank.gif");var b=0}else a.src=a.src.replace("blank.gif","checked.png"),b=1;$("#lcarddav_addressbook"+c).css("visibility","visible");rcmail.http_post("plugin.carddav-autocomplete-save","_remote=1&_autocomplete="+b+"&_id="+c)},carddav_server_index=function(a){var c=a.id.replace("s",""),b=a.value,d="";try{var e=a.className.replace("c",""),f=$($(".c"+a.value)).get(0).id.replace("s",
""),d="&_old_target_id="+f+"&_old_target_idx="+e;$("#lcarddav_addressbook"+f).css("visibility","visible")}catch(j){}$(".c"+a.value).val(e);$("#lcarddav_addressbook"+c).css("visibility","visible");rcmail.http_post("plugin.carddav-idx-save","_remote=1&_target_id="+c+"&_target_idx="+b+d)},carddav_server_add=function(){try{var a=rcube_find_object("_label"),c=rcube_find_object("_server_url"),b=rcube_find_object("_username"),d=rcube_find_object("_password"),e=rcube_find_object("_read_only"),f=rcube_find_object("_autocomplete"),
j=rcube_find_object("_idx");if(""==a.value||""==c.value)""==a.value&&""==c.value||rcmail.display_message(rcmail.gettext("settings_empty_values","carddav"),"error");else{rcmail.http_post("plugin.carddav-server-save","_remote=1&_idx="+$.base64Encode(j.value)+"&_label="+$.base64Encode(a.value)+"&_server_url="+c.value+"&_username="+$.base64Encode(b.value)+"&_password="+$.base64Encode(d.value)+"&_read_only="+$.base64Encode(!0===e.checked?"1":"0")+"&_autocomplete="+$.base64Encode(!0===f.checked?"1":"0"),
rcmail.display_message(rcmail.gettext("settings_init_server","carddav"),"loading"));parent.parent.getIFRAMEDiv("addressbook");var k=parent.parent.rcmail.env.tabbed_target.replace("#tabbed_","tabbed_frame_"),g=window.top.frames[k].document.location.href,h=g.split("_task="),g="./?_task="+h[1],h=g.split("&_s="),g=h[0]+"&_onload=no&_s="+(new Date).getTime();window.top.frames[k].document.location.href=g;window.setTimeout("parent.tabbed_syncTitle()",1E3)}}catch(l){}},carddav_server_message=function(a){if(a.check){$("#carddav_server_list").slideUp();
var c="larry"==rcmail.env.skin?$("table.propform").get(0):$("table").get(0);$(c).html('<tbody><tr><td style="width: auto;">'+a.server_list+"</td></tr></tbody>");$("table.propform td").css("width","auto");$("#carddav_server_list").slideDown();var b="confirmation";a.type&&(b=a.type);if(a.tabbed&&"function"==typeof parent.parent.getIFRAMEDiv)try{parent.parent.getIFRAMEDiv("addressbook");var c=parent.parent.rcmail.env.tabbed_target.replace("#tabbed_","tabbed_frame_"),d=window.top.frames[c].document.location.href,
e=d.split("_task="),d="./?_task="+e[1],e=d.split("&_s="),d=e[0]+"&_onload=no&_s="+(new Date).getTime();window.top.frames[c].document.location.href=d;window.setTimeout("parent.tabbed_syncTitle()",1E3)}catch(f){}rcmail.display_message(a.message,b)}else rcmail.display_message(a.message,"error")},carddav_server_success=function(a){window.setTimeout("$('.loadingsmall').css('visibility', 'hidden');",1E3);if(a.tabbed&&"function"==typeof parent.parent.getIFRAMEDiv)try{parent.parent.getIFRAMEDiv("addressbook");
var c=parent.parent.rcmail.env.tabbed_target.replace("#tabbed_","tabbed_frame_"),b=window.top.frames[c].document.location.href,d=b.split("_task="),b="./?_task="+d[1],d=b.split("&_s="),b=d[0]+"&_onload=no&_s="+(new Date).getTime();window.top.frames[c].document.location.href=b;window.setTimeout("parent.tabbed_syncTitle();",1E3)}catch(e){}rcmail.display_message(a.message,"confirmation")}};